#!/bin/bash
# MasterX Legacy File Cleanup Script
# Generated by Legacy File Analyzer

echo '🧹 Starting MasterX legacy file cleanup...'

# Create backup directory
BACKUP_DIR='./legacy_backup_$(date +%Y%m%d_%H%M%S)'
mkdir -p $BACKUP_DIR
echo '📦 Created backup directory: $BACKUP_DIR'

# Backup streaming_intelligence_engine.py
if [ -f '/Users/Dataghost/MasterX/backend/streaming_intelligence_engine.py' ]; then
    cp '/Users/Dataghost/MasterX/backend/streaming_intelligence_engine.py' '$BACKUP_DIR/streaming_intelligence_engine.py'
    echo '✅ Backed up streaming_intelligence_engine.py'
else
    echo '⚠️  File not found: /Users/Dataghost/MasterX/backend/streaming_intelligence_engine.py'
fi

# Remove redundant files
echo '🗑️  Removing redundant files...'

if [ -f '/Users/Dataghost/MasterX/backend/streaming_intelligence_engine.py' ]; then
    rm '/Users/Dataghost/MasterX/backend/streaming_intelligence_engine.py'
    echo '🗑️  Removed streaming_intelligence_engine.py'
fi

echo '✨ Legacy file cleanup completed!'
echo '📦 Backup available at: $BACKUP_DIR'
echo '🎉 MasterX platform is now clean and optimized!'